#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Twitter.Resource", IsApplication=true)]

namespace Twitter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Twitter.Shared.Resource.String.ApplicationName = global::Twitter.Resource.String.ApplicationName;
			global::Twitter.Shared.Resource.String.Hello = global::Twitter.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int cellback = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cellchecked = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CustomSelector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MainView = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int MainView_CharactersLeft = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int MainView_DeleteCommand = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int MainView_SendCommand = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int MainView_Text = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int MainView_Tweet = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int TweetListItem = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int TweetListItem_CreatedAt = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int TweetListItem_Text = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int TweetListItem_UserName = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TweetListItem = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
