#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CloudAuction.Resource", IsApplication=true)]

namespace CloudAuction
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Macaw.UIComponents.Resource.String.ApplicationName = CloudAuction.Resource.String.ApplicationName;
			Macaw.UIComponents.Resource.String.Hello = CloudAuction.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int magnify = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int slider_blt_grn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int slider_blt_trans = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int AuctionView_AvailableCount = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int AuctionView_Condition = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int AuctionView_CurrentPrice = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int AuctionView_Description = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int AuctionView_Image = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int AuctionView_Intro = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int AuctionView_ListPrice = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int AuctionView_Name = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int AuctionView_PlaceBidCommand = 2131165194;
			
			// aapt resource value: 0x7f070005
			public const int AuctionView_TimePercentageRemaining = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int AuctionView_TimeRemaining = 2131165193;
			
			// aapt resource value: 0x7f070017
			public const int LogoutMenuItem = 2131165207;
			
			// aapt resource value: 0x7f07000c
			public const int OrderView = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int OrderView_CancelCommand = 2131165202;
			
			// aapt resource value: 0x7f07000d
			public const int OrderView_DeliveryLocation = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int OrderView_FirstName = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int OrderView_LastName = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int OrderView_MiddleName = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int OrderView_ProductList = 2131165198;
			
			// aapt resource value: 0x7f070014
			public const int ProductListItem_Description = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int ProductListItem_ListPrice = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int ProductListItem_Name = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int TextListItem = 2131165206;
			
			// aapt resource value: 0x7f07000b
			public const int mainFragmentContainer = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AuctionView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int OrderView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ProductListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TextListItem = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int MainMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Logout = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Mono_Android_Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
