#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CloudAuction.Resource", IsApplication=true)]

namespace CloudAuction
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Macaw.UIComponents.Resource.String.ApplicationName = CloudAuction.Resource.String.ApplicationName;
			Macaw.UIComponents.Resource.String.Hello = CloudAuction.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int magnify = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int slider_blt_grn = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int slider_blt_trans = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int AuctionView_AvailableCount = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int AuctionView_Condition = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int AuctionView_CurrentPrice = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int AuctionView_Description = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int AuctionView_Image = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int AuctionView_Intro = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int AuctionView_ListPrice = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int AuctionView_Name = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int AuctionView_PlaceBidCommand = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int AuctionView_TimePercentageRemaining = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int AuctionView_TimeRemaining = 2131099657;
			
			// aapt resource value: 0x7f060013
			public const int LogoutMenuItem = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int OrderView = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int OrderView_CancelCommand = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int OrderView_DeliveryLocation = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int OrderView_FirstName = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int OrderView_LastName = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int OrderView_MiddleName = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int TextViewItem = 2131099666;
			
			// aapt resource value: 0x7f06000b
			public const int mainFragmentContainer = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AuctionView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int OrderView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TextViewItem = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int MainMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Logout = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
